#define TOPIC_FVE "TOPIC_FVE"
#define TOPIC_FVE_STATE "TOPIC_FVE_STATE"
#define TOPIC_FVE_DIAG "TOPIC_FVE_DIAG"
#define TOPIC_FVE_FAULT "TOPIC_FVE_FAULT"

#define BEL_ENABLED 0
#define BEL_RX_PIN 16
#define BEL_TX_PIN -1
#define BEL_RX_BUFFER_SIZE 4096
#define BEL_WH_PER_UNIT 10
#define BEL_DELTA_MAX_UNITS 1000
#define BEL_SILENCE_TIMEOUT_MS 150000UL
#define BEL_FAULT_MIN_VOLTAGE 150
#define BEL_FAULT_MIN_POWER 300
#define BEL_FAULT_CLEAR_MIN_POWER 50

#define DET_PIN_A 34
#define DET_PIN_B 35
#define DET_TH_STATE 100
#define DET_TH_CONDUCT 512
#define DET_STATE_MAJORITY 50
#define DET_STATE_OFF 40
#define DET_DROPOUT_BATCHES 4
#define DET_DROPOUT_MIN_RUN 20
